# Generated by Django 3.0.8 on 2020-07-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
            ],
        ),
    ]
