# Generated by Django 3.1.1 on 2020-09-14 02:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200913_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='resumen',
            field=ckeditor.fields.RichTextField(verbose_name='Resumen'),
        ),
    ]
