# Generated by Django 3.1.1 on 2020-09-15 20:03

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200915_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='resumen',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
