# Generated by Django 3.1.1 on 2020-09-24 13:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200915_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='resumen',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
