# Generated by Django 3.1.2 on 2020-10-21 02:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200924_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='resumen',
            field=ckeditor.fields.RichTextField(verbose_name='Resumen'),
        ),
    ]
